name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd ubuntu/standard/5.0
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
